In [2]:
import pandas as pd
import numpy as np
import glob

path = r'C:/Users/Ray/Desktop/DidaticaTech/JUN2020' # use your path
all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, encoding="ISO-8859-1", sep=',', header=1)
    dados = df.iloc[6:,[0,1,2,3,4,5,6,7,8]]
    li.append(dados)

frame = pd.concat(li, axis=0, ignore_index=True)

In [3]:
#converte formato das colunas
frame.Label = pd.to_datetime(frame.Label)
frame.Ed0305 = frame.Ed0305.replace('[^\d.]', '', regex=True).astype(float)
frame.Ed0313 = frame.Ed0313.replace('[^\d.]', '', regex=True).astype(float)
frame.Ed0320 = frame.Ed0320.replace('[^\d.]', '', regex=True).astype(float)
frame.Ed0340 = frame.Ed0340.replace('[^\d.]', '', regex=True).astype(float)
frame.Ed0380 = frame.Ed0380.replace('[^\d.]', '', regex=True).astype(float)
frame.Ed0395 = frame.Ed0395.replace('[^\d.]', '', regex=True).astype(float)
frame.Ed0PAR = frame.Ed0PAR.replace('[^\d.]', '', regex=True).astype(float)

In [4]:
frame

,Label,Ed0Gnd,Ed0305,Ed0313,Ed0320,Ed0340,Ed0380,Ed0395,Ed0PAR
0,2020-01-06 00:00:20,4.353846E-05,2.328788,2.794245,6.524796,3.581940,5.735656,2.979577,1.666289
1,2020-01-06 00:00:41,4.452381E-05,2.324106,3.155921,6.601092,3.539717,4.771944,2.963276,1.668402
2,2020-01-06 00:01:01,0.0000443,2.322959,3.092106,6.594509,3.917808,6.719106,2.972952,1.667456
3,2020-01-06 00:01:21,0.0000442,2.311091,3.143747,6.609080,3.317276,6.104958,2.915988,1.662289
4,2020-01-06 00:01:41,4.305E-05,2.330502,2.970750,6.643398,3.436173,5.228311,2.985449,1.650455
...,...,...,...,...,...,...,...,...,...
129548,2020-06-30 23:58:22,0.0000425,1.939065,2.085110,7.506909,1.928797,7.328302,3.105220,2.186618
129549,2020-06-30 23:58:42,0.0000424,1.935193,2.265853,7.565193,2.414462,5.812742,3.131350,2.193812
129550,2020-06-30 23:59:02,0.0000428,1.950530,1.863055,7.585132,2.428569,6.946935,3.128590,2.195796
129551,2020-06-30 23:59:22,0.0000426,1.951385,1.881129,7.490230,2.003360,7.258962,3.142223,2.223608
129552,2020-06-30 23:59:42,4.275E-05,1.935293,1.772683,7.525698,2.509177,7.823583,3.118691,2.123862

In [80]:
# Coluna 'Data'
frame['Data'] = frame.Label.dt.strftime('%Y-%d-%m')
# Coluna 'Hora'
frame['Hora'] = frame.Label.dt.strftime('%H:%M:%S')

In [69]:
grouped = frame[['Ed0305', 'Ed0313']].groupby(frame['Label'])
#'Ed0320','Ed0340','Ed0380','Ed0395','Ed0PAR'

In [72]:
grouped.max()

                       Ed0305    Ed0313
Label
2020-01-06 00:00:20  2.328788  2.794245
2020-01-06 00:00:41  2.324106  3.155921
2020-01-06 00:01:01  2.322959  3.092106
2020-01-06 00:01:21  2.311091  3.143747
2020-01-06 00:01:41  2.330502  2.970750
...                       ...       ...
2020-12-06 23:58:21  2.082384  3.719542
2020-12-06 23:58:41  2.080121  4.106849
2020-12-06 23:59:01  2.083993  3.574948
2020-12-06 23:59:21  2.076249  3.988075
2020-12-06 23:59:41  2.096314  3.234119

[129553 rows x 2 columns]